### ISSUE TITLE
Initial GUI size shrunk to a state of unusability

### ISSUE THREAD

**Issue by relleoML** [svenssonaxel/pdf-sign#10]
Thanks for this great tool I've been anticipating for years! It works like a charm!

However, I found this oddity that the GUI always opens up in a quite unusable state (see screener) - i.e. the window canvas is shrunk to a few pixels.

![shrunk GUI](https://github.com/svenssonaxel/pdf-sign/assets/101594944/6a2f39e7-50ba-4a90-bad5-3286c1d92ab1)

In another issue I read [something similar](https://github.com/svenssonaxel/pdf-sign/issues/5#issuecomment-1686334070).

Its not a big deal to drag and enlarge the window in first x- and then y- direction, but its 2 unnecessary interactions imho. Enlarging it diagonally makes the tool crush with the following error: 
> `
Unrecoverable error: rangecheck in .putdeviceprops
Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET', '-sOutputFile=/tmp/tmpry7ko1k6/display.png', '-sDEVICE=pngalpha', '-dMaxBitmap=2147483647', '-dDEVICEWIDTHPOINTS=-1', '-dDEVICEHEIGHTPOINTS=-1', '-dFIXEDMEDIA', '-dPDFFitPage', '-f', '/tmp/tmpry7ko1k6/signed-page.pdf']' returned non-zero exit status 255.
 `  

I suppose its a tkinter issue, but the error seems to somehow imply otherwise.

I am using Ubuntu and Gnome shell if that matters somehow.

**Comment by svenssonaxel** [comment]
@relleoML Please try branch `dev`. Can you confirm whether the fix works for you?

**Comment by relleoML** [comment]
@svenssonaxel Yes, branch dev resolves this issue. Thanks! How do we go from here?

**Comment by svenssonaxel** [comment]
@relleoML Merged to master.
