### ISSUE TITLE
Error: PDF is unusable as a signature. Reason unknown.

### ISSUE THREAD

**Issue by rocketraman** [svenssonaxel/pdf-sign#14]
I reproduced the problem I initially mentioned in https://github.com/svenssonaxel/pdf-sign/issues/13, but I figured it was better to create a separate issue to track it.

Attached is a test signature PDF that crashes pdf-sign with the error message:

PDF is unusable as a signature. Reason unknown.

[test-signature.pdf](https://github.com/user-attachments/files/16918732/test-signature.pdf)

**Comment by svenssonaxel** [comment]
Pushed a tentative fix to `dev` branch. Seems to work with the signature you supplied, but I'd love to see if it can still be broken.

Thank you for continuous and detailed bug reports, they are great help.

**Comment by rocketraman** [comment]
Ooh yeah double equality will get you every time :-) Glad you found it. Dev branch works for me with that signature, as well as my actual sigs.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
