### ISSUE TITLE
Such a great tool!

### ISSUE THREAD

**Issue by erwin** [svenssonaxel/pdf-sign#2]
Thank you for putting this together!

Amazing how difficult it is to sign a PDF on Linux compared to the feature for it built into Preview.app on Mac OS X.

Great little app.

Maybe add some screenshots or an animated .GIF to the README.md?

Also, please consider posting the blank 2x3" pdf right on the README page rather than generating it locally.

**Comment by svenssonaxel** [comment]
@erwin Your comments on https://github.com/svenssonaxel/pdf-sign/tree/issue-2 please?

**Comment by erwin** [comment]
Looks fantastic!

Nice job putting that screen cast together!

And the link to download the PDF is super helpful!

Thanks so much!
