### ISSUE TITLE
Weird artifact after signature

### ISSUE THREAD

**Issue by Vaelatern** [svenssonaxel/pdf-sign#7]
I used an existing PDF, which was cropped from an image, and the background made transparent. I ended up with an outline on the top and right of the signature in the resulting PDF.

I can share the signature or I can try to duplicate using public data to help demonstrate.

**Comment by svenssonaxel** [comment]
@Vaelatern I'm not very optimistic that it's something I can fix, but if you can reproduce with public data and share in this issue, then at least I might be able to determine the source of the artifact. If you do so, please share both the image and the signature PDF.

**Comment by svenssonaxel** [comment]
@Vaelatern I'll close this for now. Feel free to reopen if you still have problems.
